### ISSUE TITLE
Improperly formatted error message

### ISSUE THREAD

**Issue by Urkchar** [sns-sdks/python-youtube#101]
When receiving an error message for going over your quota, the message says `The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.`. It should probably say `The request cannot be completed because you have exceeded your quota.` instead. 
This is caused by the code found in `error_handler` of the `PyYouTubeException` class in the `error.py` file. Linked here https://github.com/sns-sdks/python-youtube/blob/561b64f897861a399c67ffc1de2f18b8ae91cdef/pyyoutube/error.py#L42
This behavior is caused when creating a `PyYouTubeException` instance by passing a `Response` to the `__init__`. You can see that in the `_parse_response` method of the `Api` class in the `api.py` file linked here https://github.com/sns-sdks/python-youtube/blob/561b64f897861a399c67ffc1de2f18b8ae91cdef/pyyoutube/api.py#L292
The reason why this is important is because we needed to know whether to change the `if` or the `elif` in the `error_handler` of `PyYouTubeException`. Since we know that we are passing a `Response`, we know that we need to change the `elif`. We set the `self.message` to `res_data["error"]["message"]` which would normally work however that value is not what we expect it to be. We want the message to be `The request cannot be completed because you have exceeded your quota.` however that's not what's given to us by the response. We are given `The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.` by the response. 
This can be fixed by modifying the `error_handler` to format this error message. Here's a code sample of how the fix might look. 
```py
    def error_handler(self):
        """
        Error has two big type(but not the error type.): This module's error, Api return error.
        So This will change two error to one format
        """
        if isinstance(self.response, ErrorMessage):
            self.status_code = self.response.status_code
            self.message = self.response.message
            self.error_type = "PyYouTubeException"
        elif isinstance(self.response, Response):
            res_data = self.response.json()
            if "error" in res_data:
                self.status_code = res_data["error"]["code"]
                if res_data["error"]["message"] == 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.':
                    self.message = "The request cannot be completed because you have exceeded your quota."
                else:
                    self.message = res_data["error"]["message"]
                self.error_type = "YouTubeException"
```

**Comment by MerleLiuKun** [comment]
I konw your mean, but may this have better way to handle this, I will think it.:)

**Comment by Urkchar** [comment]
> I konw your mean, but may this have better way to handle this, I will think it.:)

What ideas do you have for handling this?

**Comment by MerleLiuKun** [comment]
I think you may extract it outside, in this library,may not for this. :)
