### ISSUE TITLE
the snippet for comment info obtained from get_comment_by_id() doesn't give other snippet properties apart from authorDisplayName and likeCount

### ISSUE THREAD

**Issue by sshivprasad** [sns-sdks/python-youtube#104]
I am calling get_comment_by_id() and explicitly passing the parts as 'snippet', but the result doesn't include other snippet comment properties like textDisplay, textOriginal, publishedAt, updatedAt etc. Are these properties currently supported?

![image](https://user-images.githubusercontent.com/37325502/130803947-207ede66-4a02-4c25-85c6-84b6226a5f0c.png)
![image](https://user-images.githubusercontent.com/37325502/130804024-16f1a301-33ba-4e29-a58b-c2fc2a52206f.png)

**Comment by MerleLiuKun** [comment]
You can call the `comment.publishedAt` to show it. `print` will only show some fields.
