### ISSUE TITLE
Not finding channel even though channel exists

### ISSUE THREAD

**Issue by Urkchar** [sns-sdks/python-youtube#107]
Code:
```py
import pyyoutube


API_KEY = "xxx"   # Your api key here
CHANNEL_LINK = "https://www.youtube.com/c/kbsworldtv"
CHANNEL_IDENTIFIER = "kbsworldtv"
api = pyyoutube.Api(api_key=API_KEY)

channel_res_by_name = api.get_channel_info(channel_name=CHANNEL_IDENTIFIER)
channel_res_by_id = api.get_channel_info(channel_id=CHANNEL_IDENTIFIER)

print(f"channel_res_by_name: {channel_res_by_name}")
print(f"channel_res_by_name.items: {channel_res_by_name.items}")

print(f"channel_res_by_id: {channel_res_by_id}")
print(f"channel_res_by_id.items: {channel_res_by_id.items}")
```
Output:
```
channel_res_by_name: ChannelListResponse(kind='youtube#channelListResponse')
channel_res_by_name.items: None
channel_res_by_id: ChannelListResponse(kind='youtube#channelListResponse')
channel_res_by_id.items: None
```
Why can't I find this channel? If you go to the URL at `CHANNEL_LINK`, you will see that it is a valid channel. I tried finding the channel using `kbsworldtv` as both a `channel_name` and `channel_id` but neither worked. 
If you need information, please let me know.

**Comment by MerleLiuKun** [comment]
This same as #86

**Comment by Urkchar** [comment]
Okay. I'd like to make a feature request to be able to get channel info using the customUrl.

**Comment by MerleLiuKun** [comment]
Hi,

The parameter `channel_name` may be named incorrect.  Refer the [docs](https://developers.google.com/youtube/v3/guides/working_with_channel_ids) we can know, the username is the old version youtube's properities. 

I guess keep this parameter maybe backwards compatibility。

If you want get channle by the channel name, maybe need use the `search` methods.

And, for the [channel docs](https://developers.google.com/youtube/v3/docs/channels/list), there not have paramter for the `customUrl`. So this not support. :)

**Comment by MerleLiuKun** [comment]
Another answer: 

https://stackoverflow.com/questions/64299967/how-to-find-the-forusername-parameter-for-a-specific-channel
