### ISSUE TITLE
bannerExternalUrl

### ISSUE THREAD

**Issue by efendihassan** [sns-sdks/python-youtube#109]
Hi and good day.

how do i get bannerExternalUrl from channel class ?
I used Api.get_channel_info(channel_id="xxx", parts="snippet,brandingSettings")
to retrieve channel class.

thank you in advance

**Comment by MerleLiuKun** [comment]
As the [docs](https://developers.google.com/youtube/v3/docs/channels#brandingSettings.image.bannerExternalUrl) says. The `image`  property and all of its child properties have been deprecated. 

So the model has removed it.

If you want to get it, you can use the parameter `return_json=True` to get original data.
