### ISSUE TITLE
Playlist name (accessing a channels uploaded playlist)

### ISSUE THREAD

**Issue by JoshPaulie** [sns-sdks/python-youtube#117]
👋🏼 I've used python-YouTube for a bit of a year now. It's not too shabby, but the docs are kinda convoluted.

Is there anyway to get a playlist's name? It seems to only returns the type and id, which isn't any useful for me trying to find a channel's "Uploads" playlist

**Comment by MerleLiuKun** [comment]
> Is there anyway to get a playlist's name? It seems to only returns the type and id, which isn't any useful for me trying to find a channel's "Uploads" playlist

If I understand correctly. If you want to get `name` for a playlist, you may
```
>>> resp = api.get_playlist_by_id(playlist_id="UU_x5XG1OV2P6uZZ5FSM9Ttw", parts="snippet")
>>> playlist = resp.items[0]
>>> playlist.snippet.title
# 'Uploads from Google Developers'
```
> It seems to only returns the type and id,

Because the response is covered by the dataclass, And the default repr is only appear kind, id.

**Comment by JoshPaulie** [comment]
Thanks! I understand now. What would be the best way to get any channel's uploads playlist id? I noticed you passed Google's directly. I figured it would be the first playlist returned but I was incorrect

**Comment by MerleLiuKun** [comment]
I would give you a link, you can follow this. `https://webapps.stackexchange.com/a/113913`, And this is magick.

**Comment by JoshPaulie** [comment]
That is magic! Thank you!
