### ISSUE TITLE
How to get list of all videos in one channel? 

### ISSUE THREAD

**Issue by karolzlot** [sns-sdks/python-youtube#119]
Hi, how I could achieve it with this library? 

I can't figure it out.

More info about what I want to achieve:

https://stackoverflow.com/questions/18953499/youtube-api-to-fetch-all-videos-on-a-channel

**Comment by MerleLiuKun** [comment]
In #117 , You can use that magic to get all published videos.

**Comment by karolzlot** [comment]
Thank you, it works.

Then I used `playlist_item_by_playlist = api.get_playlist_items(playlist_id="UU.......", count=2)` to have list of videos.
