### ISSUE TITLE
wanted: update playlists

### ISSUE THREAD

**Issue by lsloan** [sns-sdks/python-youtube#141]
I notice in the README that updates to YouTube data via the API is one of the "To Dos" for future work.  I'd really like to see that.  I noticed this Python module because I was looking for an easy solution to let me edit playlists in my YouTube channel.

**Comment by MerleLiuKun** [comment]
hi,

As the docs says, We have provide new `Client` class to operate YouTube DATA API.

You can see this [docs](https://github.com/sns-sdks/python-youtube/blob/master/docs/docs/usage/work-with-client.md) to get detail for `Client`. 

And the `playlists` resource just like `videos` resource.

And this is a pre release, It will release recently.

**Comment by MerleLiuKun** [comment]
#120
