### ISSUE TITLE
The Response item has method `_json`, but not `json`

### ISSUE THREAD

**Issue by jonsel087** [sns-sdks/python-youtube#148]
https://github.com/sns-sdks/python-youtube/blob/99d7a2c38840711b2c6e206a5b89fc150543f32b/pyyoutube/client.py#L150-L155

Believe that it should be `data = response.to_json()`, 
Since `json` method dos not exist for `<class 'pyyoutube.models.video.VideoListResponse'>`

**Comment by MerleLiuKun** [comment]
this `response` is requests Response. not the xxxResponse
