### ISSUE TITLE
Requesting client.channels.list with for_username

### ISSUE THREAD

**Issue by dj2ball** [sns-sdks/python-youtube#158]
I am struggling to use the for_username argument to request a client channel list. Example code below:

-------------------------------
from pyyoutube import Client
import json

#Youtube Data API V3
API_KEY = "XXX"

client = Client(api_key = API_KEY)

#response = client.channels.list(channel_id="UCMo28ATCDU0Kn9dpilAF79Q", return_json=True)
response = client.channels.list(for_username="@TheOverlap", return_json=True)

print(json.dumps(response))

RESPONSE: {"kind": "youtube#channelListResponse", "etag": "RuuXzTIr0OoDqI4S0RU6n4FqKEM", "pageInfo": {"totalResults": 0, "resultsPerPage": 5}}

**Comment by MerleLiuKun** [comment]
The `for_username` is not for the new username for the channel.  And This `username` is in the old youtube version,  

You can get more information at [doc](https://developers.google.com/youtube/v3/docs/channels/list)

**Comment by fireattack** [comment]
I assume there is no API for the "new" username yet?

**Comment by MerleLiuKun** [comment]
As of now, tthe field `custom_url` (at the channel snippet part) will return this new username data, but there is no place to use this username to fetch other data.

**Comment by MerleLiuKun** [comment]
#169
