### ISSUE TITLE
how to get all channels list in you tube?

### ISSUE THREAD

**Issue by jossiekat** [sns-sdks/python-youtube#55]
I can only get one Chanel  that I know of and i'm interested in all.
can Ido that with this api?

**Comment by MerleLiuKun** [comment]
Sorry, Can you provide more info? 

If you want all channel on YouTube.com, not have that apis. But you can use search api to get channels and try more times and save the data.

**Comment by jossiekat** [comment]
what i want is list of all channels in youtube.
currently current api enables me to get info on a single channel which I know it's id or name.

"But you can use search api to get channels and try more times and save the data."
yes - this is exactly what I want!
can you show me how to do it?
what search api ?

**Comment by MerleLiuKun** [comment]
In fact, you can not get all, but you can see docs as follows:

- [search-channels](https://developers.google.com/youtube/v3/guides/implementation/search#search-channels).
- [search api](https://developers.google.com/youtube/v3/docs/search/list)

And use this library, you can use methods:

- [Search](https://github.com/sns-sdks/python-youtube#search)
