### ISSUE TITLE
How to get tags of a video ?

### ISSUE THREAD

**Issue by lukelu0520** [sns-sdks/python-youtube#56]
Dear sns-sdks,

After searching and getting some search results, I was wondering how to get tags used by these video ?

Hope to hear your expertise.

Thank you.

**Comment by MerleLiuKun** [comment]
You can get video info by the method `api.get_video_by_id(video_id="CvTApw9X8aA",parts=["id", "snippet"])`。

The part of `snippet` has the tags data. 

You can find more info at docs [Video tags](https://developers.google.com/youtube/v3/docs/videos#snippet.tags[])
