### ISSUE TITLE
tag madeforkids not available

### ISSUE THREAD

**Issue by EhtishamSabir** [sns-sdks/python-youtube#59]
the tag made for kids is not available in python api you have to fix that.

**Comment by EhtishamSabir** [comment]
in video.py of python-youtube library add these two lines

    madeForKids: Optional[bool] = field(default=None, repr=False)
    selfDeclaredMadeForKids:Optional[bool] = field(default=None, repr=False)

**Comment by MerleLiuKun** [comment]
Hey, 
    Thanks for your issue. I will check and fix this quickly. :)

**Comment by EhtishamSabir** [comment]
perfect guys thank you!

**Comment by EhtishamSabir** [comment]
thank you very much perfect!
