### ISSUE TITLE
Retrieve all videos from channel

### ISSUE THREAD

**Issue by julian59189** [sns-sdks/python-youtube#65]
How can I retrieve all videos from one channel?
I didn't find that feature.
Thanks!

**Comment by MerleLiuKun** [comment]
Hi, 

   Sorry for late reply, I have provide a [exmaple](https://github.com/sns-sdks/python-youtube/blob/master/examples/channel_videos.py) to get channel videos. You can follow that.

**Comment by julian59189** [comment]
Thank you! I will test it!
