### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by Hunter2807** [sns-sdks/python-youtube#90]
Hey! 

I am trying to make a discord bot using this, which would notify the users of **every** video which would be uploaded. I have got the way to get all rhe videos of the channel. Now I want a way to get the timestamps of the videos, which are on the channel. How do i get the timestamps, and if possible, can u also tell me how this would work? If there's any other way to check for new videos...

**Comment by MerleLiuKun** [comment]
the timestamps of the videos is the field `publishedAt` in the `snippet` part. 

You can try it.:)

**Comment by Hunter2807** [comment]
Hey @MerleLiuKun, I wanted to know, what would be the easiest way to print something, whenever a new video is uploaded? (Ik I have exchanged bot with print for the sake of easiness). Well I want a way which is the fastest... Help would be appreciated.

**Comment by MerleLiuKun** [comment]
Sorry, I don't know your mean, print,  you mean `print` function?  where you will print.
