### ISSUE TITLE
Any plans to implement the 'statistics' part?

### ISSUE THREAD

**Issue by bobtoovey** [sns-sdks/python-youtube#91]
Just a quick question, 

I'm using the 'api.get_activities_by_channel' function to get a list of videos from a channel ID. I can get the snippets and contentDetails parts just fine, but not statistics. 

I have tried to add parts=["contentDetails", "snippet", "statistics"] but I get an error raised, "Parts statistics for resource activities not support"

Any chance of getting this supported? 

Otherwise, great library!

Bob

**Comment by MerleLiuKun** [comment]
Hello, I have checked the [docs](https://developers.google.com/youtube/v3/docs/activities#resource),

This endpoint not support the part `statistics`,  You can look the docs and check it.

Thanks still. :)

**Comment by bobtoovey** [comment]
Ok fair enough! Thanks for responding...

Cheers

Bob
