### ISSUE TITLE
could not import pyyoutube after installation.

### ISSUE THREAD

**Issue by voipmanvn** [sns-sdks/python-youtube#99]
Hello, 

I could not import pyyoutube. check error log

(kivy_venv) thanhtruonglabs:site-packages macbook$ python
Python 3.9.2 (default, Mar 29 2021, 22:28:36) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyyoutube
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyyoutube'

pip freeze return installation packages:
python-youtube==0.8.1

Please check

**Comment by MerleLiuKun** [comment]
hi 

I have checked this, it works well for me,

You can check your venv, is command `pip freeze` and `python` in the same env :)
